### ISSUE TITLE
Core version 7.15 appears to be breaking v7.9.2

### ISSUE THREAD

**Issue by twiggy** [bugsnag/bugsnag-js#1657]
We have a dependency on 7.9.2

Looking at its package.json it depends on core ^7.9.2 so when core 7.15 came out today was used by js 7.9.2

We are not getting an error during npm install, but basically node_modules/@bugsnag/node/dist isn't there and so the module doesn't load.

Error: Cannot find module '/opt/xxxx/node_modules/@bugsnag/node/dist/bugsnag.js'

We will most likely update our package to latest, but shouldn't one version of bugsnag-js depend on the same basic version of bugsnag-core ... like maybe 7.9.2 would use core 7.9.3 but not 7.15

Can replicate with 

npm install @bugsnag/js@7.9.2 then look at node_modules folder and notice no dist folder

bugsnagtest/node_modules/@bugsnag/node

Thanks!

**Comment by imjoehaines** [comment]
Hey @twiggy, sorry about this — we had an issue with the release which prevented the built files from being included

We're working on publishing v7.15.1 to fix this, which should be available shortly. I'll update this issue when it's available
