### ISSUE TITLE
Build fails Xcode 13 - error: duplicate interface definition for class 'BugsnagApp'

### ISSUE THREAD

**Issue by squareborg** [bugsnag/bugsnag-js#1537]
### Describe the bug
A new install of Bugsnag react native fails to build in Xcode 13.0, first time using the RN bugsnag so unsure if its me

### Steps to reproduce
Follow the install docs https://docs.bugsnag.com/platforms/react-native/react-native/
Initiate a build in Xcode
See 30 issues under Bugsnag
### Environment
* Bugsnag version:   "@bugsnag/react-native": "^7.13.1",
* React Native:  "react-native": "0.63.4",

<details><summary>Error messages:</summary>

/Users/xxx/Code/xxx/xxx/node_modules/@bugsnag/react-native/ios/vendor/bugsnag-cocoa/Bugsnag/include/Bugsnag/BugsnagApp.h:15:1: error: duplicate interface definition for class 'BugsnagApp'

</details>

**Comment by squareborg** [comment]
Ahh my fault, I added `pod 'Bugsnag'`  to my Podfile `ios/Podfile` and this I think made it try to compile twice resulting in the `duplicate interface definition`
